---
title: "Worksheet#4C"
author: "Marivic Amuan"
date: "2023-11-22"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}

#1. Use the dataset mpg

#1A. Show your solutions on how to import a csv file into the environment.

library(readr)

mpg <- read_csv("mpg.csv")

head(mpg)

```

```{r}

#1B. Which variables from mpg dataset are categorical?

str(mpg)

```

```{r}
#1C. Which are continuous variables?
#
summary(mpg)

```

```{r}
#2. Which manufacturer has the most models in this data set? Which model has the most variations? Show your answer.

#ANSWER: THE MOST MODEL MANUFACTURER IS DODGE.THE MOST VARIATION IS CARAVAN 2WD.

model <- mpg %>%
 group_by(manufacturer) %>%
 summarise(count = n()) %>%
 arrange(desc(count))

print(model)

count <- mpg %>%
 group_by(model) %>%
 summarise(variation = n()) %>%
 arrange(desc(variation))

print(count)

```


```{r}
#2A. What does ggplot(mpg, aes(model, manufacturer)) + geom_point() show?



```

```{r}
#2A. Group the manufacturers and find the unique models. Show your codes and result.

manufacturer_models <- unique(mpg[, c("manufacturer", "model")])
manufacturer_models

```


```{r}
#2B. Graph the result by using plot() and ggplot(). Write the codes and its result.

ggplot(mpg, aes(x = model, y = manufacturer, color = class)) + 
  geom_point() +
  labs(title = "Car Models and Manufacturers",
       x = "Car Model",
       y = "Manufacturer",
       color = "Class") +
  theme_minimal() +
  theme(legend.position = "right", axis.text.x = element_text(angle = 90,hjust = 1),
        plot.title = element_text(hjust = 0.5))

```

```{r}
#2. Same dataset will be used. You are going to show the relationship of the model and the manufacturer


```