---
title: "RWorksheet#4A"
author: "Marivic Amuan"
date: "2023-10-28"
output: pdf_document
---

```{r name, echo = TRUE }
#1. The table below shows the data about shoe size and height. Create a data frame.

#1A. Describe the data = AS I input each correspoding data inside the data frame, the data.frame allows me to create a table file to show the inputted datas.

householdData <- data.frame(
  ShoeSize = c(6.5,9.0, 8.5, 8.5, 10.5, 7.0, 9.5, 9.0, 13.0, 7.5, 10.5, 8.5, 12.0, 10.5, 13.0, 11.5, 8.5, 5.0, 10.0, 6.5, 7.5, 8.5, 10.5, 8.5, 10.5, 11.0, 9.0, 13.0),
  Height = c(66.0, 68.0, 64.5, 65.0, 70.0, 64.0, 70.0, 71.0, 72.0, 64.0, 74.5, 67.0, 71.0, 71.0, 77.0, 72.0, 59.0, 62.0, 72.0, 66.0, 64.0, 67.0, 73.0, 69.0, 72.0, 70.0, 69.0, 70.0),
  Gender = c("F", "F", "F", "F", "M", "F", "F", "F", "M", "F", "M", "F", "M", "M", "M", "M", "F", "F", "M", "F", "F", "M", "M", "F", "M", "M", "M", "M")
)

householdData

write_csv(householdData, "householdData.csv",)

```

``` {r}
#1B. Create a subset by males and females with their corresponding shoe size and height. What its result? Show the R scripts.


subsetMale <- householdData[householdData$Gender == "M", c("ShoeSize", "Height", "Gender")]
subsetMale

subsetFemale <- householdData[householdData$Gender == "F", c("ShoeSize", "Height", "Gender")]
subsetFemale


#1C. Find the mean of shoe size and height of the respondents. Write the R scripts and its result.

meanShoeSize <- mean(householdData$ShoeSize)
meanShoeSize

#RESULT: [1] 9.410714

meanHeight <- mean(householdData$Height)
meanHeight

#RESULT: [1] 68.57143

#1D. Is there a relationship between shoe size and height? Why? 
#ANSWER: There could be a relationship between shoe size and height because 

correlation <- cor(householdData$ShoeSize, householdData$Height)
correlation

#RESULT: [1] 0.7766089
```

``` {r} 
#2. Construct character vector months to a factor with factor() and assign the result to factor_months_vector. Print out factor_months_vector and assert that R prints out the factor levels below the actual values.

months <- c("March","April","January","November","January", "September","October","September","November","August", "January","November","November","February","May","August", "July","December","August","August","September","November","February", "April")
months

monthsFactor <- factor(months)
monthsFactor
```

``` {r}
#3. Then check the summary() of the months_vector and factor_months_vector. Interpret the results of both vectors. 
#Are they both equally useful in this case? =

summary(months)

summary(monthsFactor)

#4. Create a vector and factor for the table below.

direction <- c("East", "West", "North")
direction

freq <- c(1 ,4, 3)
freq

new_order_data <- factor(direction,levels = c("East","West","North") , c(1,4,3))
print(new_order_data)

#5. Enter the data below in Excel with file name = import_march.csv

imported <- read.table(file = "/cloud/project/Worksheet#4A/import_march.csv", header = TRUE, sep = ",")
    imported
    
#5A.Import the excel file into the Environment Pane using read.table() function. Write the code.

 library(readr)
     import_march <- read_csv("/cloud/project/Worksheet#4A/import_march.csv")


#5B. View the dataset. Write the R scripts and its result.

head(import_march)



#Using Conditional Statements (IF-ELSE)

#6. Full Search

num <- readline(prompt = "Enter number from 1-50: ")
paste("You Entered: ", num)

paste("Your entered number is ", num)

if(num == 50) {
  paste("The number you selected is beyond the range of 1 to 50")
  
} else if (num <= 50){
  paste("TRUE")
} else {
  paste(num)
}

#7. Change

bills <- c(50,100,200,500,1000)
bills

minimum <- function (price) {
  
  bill <- price%/% 50 
  paste("The  minimum number of bills:", bill)
}
snackprice <- 250
minimum(snackprice)


#8. The following is each student’s math score for one semester. Based on this, answer the following questions.

#8A. Create a dataframe from the above table. Write the R codes and its output.

mathGrades <- data.frame(
  name = c("Annie","Thea","Steve","Hanna"),
  grade1 = c(85,65,75,95),
  grade2 = c(65,75,55,75),
  grade3 = c(85,90,80,100),
  grade4 = c(100,90,85,90)
)
mathGrades

#8B. Without using the rowMean function, output the average score of students whose average math score over 90 points during the semester. write R code and its output.
#Example Output: Annie’s average grade this semester is 88.75.

mathGrades$average <- (mathGrades$grade1 + mathGrades$grade2 + mathGrades$grade3 + mathGrades$grade4) /4

highest <- mathGrades[mathGrades$average >= 90,]
highest

if (nrow(highest) > 0){
  paste0(highest$name, "'s grade  this semester is: ", highest$average)
} else {
    paste("No students have an average math grade over 90.")
}

#8D. Without using the mean function, output as follows for the tests in which the average score was less than 80 out of 4 tests.

test1 <- sum(mathGrades$grade1) / nrow(mathGrades)
test1

test2 <- sum(mathGrades$grade2) / nrow(mathGrades)
test2

test3 <- sum(mathGrades$grade3) / nrow(mathGrades)
test3

test4 <- sum(mathGrades$grade4) / nrow(mathGrades)
test4

if(test1 < 80){
  paste("The first test was so difficult!")
} else if (test2 < 80){
  paste("The second test is even more diffucult than the first one!")
} else if (test3 < 80){
  paste("The third test is even difficult!")
} else if (test4 < 80){
  paste("No test had an average grade less than 80")
}

#8D. Without using the max function, output as follows for students whose highest score for a semester exceeds 90 points.

  #Annie's Scores

if (mathGrades[1,2] > mathGrades[1,3] && mathGrades[1,2] > mathGrades[1,4] && mathGrades[1,2] > mathGrades[1,5]) {
  Annie <- mathGrades[1,2]
} else if (mathGrades[1,3] > mathGrades[1,4] && mathGrades[1,3] > mathGrades[1,5]) {
  Annie <- mathGrades[1,3]
} else if (mathGrades[1,4] > mathGrades[1,5] && mathGrades[1,2] > mathGrades[1,5]) {
  Annie <- mathGrades[1,4]
} else {
  Annie <- mathGrades[1,5]
}


  #Thea's Scores

if (mathGrades[2,2] > mathGrades[2,3] && mathGrades[2,2] > mathGrades[2,4] && mathGrades[2,2] > mathGrades[2,5]) {
  Thea <- mathGrades[2,2]
} else if (mathGrades[2,3] > mathGrades[2,4] && mathGrades[2,3] > mathGrades[2,5]) {
  Thea <- mathGrades[2,3]
} else if (mathGrades[2,4] > mathGrades[2,5] && mathGrades[2,2] > mathGrades[2,5]) {
  Thea <- mathGrades[2,4]
} else {
  Thea <- mathGrades[2,5]
}

  #Steve's Scores

if (mathGrades[3,2] > mathGrades[3,3] && mathGrades[3,2] > mathGrades[3,4] && mathGrades[3,2] > mathGrades[3,5]) {
  Steve <- mathGrades[3,2]
} else if (mathGrades[3,3] > mathGrades[3,4] && mathGrades[3,3] > mathGrades[3,5]) {
  Steve <- mathGrades[3,3]
} else if (mathGrades[3,4] > mathGrades[3,5] && mathGrades[3,2] > mathGrades[3,5]) {
  Steve <- mathGrades[3,4]
} else {
  Steve <- mathGrades[3,5]
}

  #Hanna's Scores
if (mathGrades[4,2] > mathGrades[4,3] && mathGrades[4,2] > mathGrades[4,4] && mathGrades[4,2] > mathGrades[4,5]) {
  Hanna <- mathGrades[4,2]
} else if (mathGrades[4,3] > mathGrades[4,4] && mathGrades[4,3] > mathGrades[4,5]) {
  Hanna <- mathGrades[4,3]
} else if (mathGrades[4,4] > mathGrades[4,5] && mathGrades[4,2] > mathGrades[4,5]) {
  Hanna <- mathGrades[4,4]
} else {
  Hanna <- mathGrades[4,5]
}

mathGrades$highest <- c(Annie, Thea, Steve, Hanna)


abovegradeof90 <- mathGrades[mathGrades$highest >= 90,]


if (nrow(abovegradeof90) > 0) {
  paste(abovegradeof90$name, "'s highest grade this semester is", abovegradeof90$highest)
} else {
  paste("No students have an average math score over 90.")
}
```
